spring:
  main:
    banner-mode: off
  application:
    name: unified-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dexterautonomy/service-configurations
          clone-on-start: true
          default-label: main
  security:
    basic:
      enabled: false
      path: /**
    ignored: /health**,/info**,/metrics**,/trace**
    user:
      name: ${CONFIG_SERVER_USERNAME}
      password: ${CONFIG_SERVER_PASSWORD}
      roles: manager
server:
  port: 9199